// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAijmW4ACTvpEL41iunoSaBzUPndOr0azc',
    appId: '1:698305738852:web:14f87654920903b9c7c771',
    messagingSenderId: '698305738852',
    projectId: 'run-fc',
    authDomain: 'run-fc.firebaseapp.com',
    storageBucket: 'run-fc.appspot.com',
    measurementId: 'G-RHWSS1DS8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnMP59nvI7zUcDZm_VXvPXa7eOTcsMYts',
    appId: '1:698305738852:android:8fb025c525407588c7c771',
    messagingSenderId: '698305738852',
    projectId: 'run-fc',
    storageBucket: 'run-fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwJ1wlmRiE2DrtThLHw2mTDeHhyqmWPOE',
    appId: '1:698305738852:ios:8f089d597a488d80c7c771',
    messagingSenderId: '698305738852',
    projectId: 'run-fc',
    storageBucket: 'run-fc.appspot.com',
    iosBundleId: 'com.example.runFc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwJ1wlmRiE2DrtThLHw2mTDeHhyqmWPOE',
    appId: '1:698305738852:ios:dc467902055d105dc7c771',
    messagingSenderId: '698305738852',
    projectId: 'run-fc',
    storageBucket: 'run-fc.appspot.com',
    iosBundleId: 'com.example.runFc.RunnerTests',
  );
}
